In [8]:
import pandas as pd
from datetime import datetime as dt

In [125]:
bike_df=pd.read_csv("./202405-citibike-tripdata_5.csv")

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1060267106.py:1: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  bike_df=pd.read_csv("./202405-citibike-tripdata_5.csv")

In [126]:
bike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,AD29C0EB02CCAB09,classic_bike,2024-05-01 16:14:42,2024-05-01 16:25:53,E 6 St & Ave B,5584.04,E 16 St & Irving Pl,5938.11,40.724537,-73.981854,40.735367,-73.987974,member
1,80DD17CA57C45921,electric_bike,2024-05-16 17:57:37,2024-05-16 18:04:30,Scholes St & Manhattan Ave,5108.01,Metropolitan Ave & Bedford Ave,5308.04,40.708651,-73.944878,40.715348,-73.960241,member
2,6EAA75427C2CB2D8,electric_bike,2024-05-23 17:02:35,2024-05-23 17:18:49,Sharon St & Olive St,5323.06,Metropolitan Ave & Bedford Ave,5308.04,40.715340,-73.938393,40.715348,-73.960241,member
3,700278157C0AC354,classic_bike,2024-05-02 06:52:23,2024-05-02 07:01:07,Prospect Park West & 8 St,3722.04,Dean St & Franklin Ave,4107.13,40.665147,-73.976376,40.677592,-73.955637,member
4,00ED91829C30FA66,electric_bike,2024-05-17 20:19:32,2024-05-17 20:33:33,E 2 St & Ave A,5553.10,Metropolitan Ave & Bedford Ave,5308.04,40.723335,-73.986055,40.715348,-73.960241,member

In [127]:
bike_csv=bike_df.dropna()

In [87]:
bike_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230297 entries, 0 to 230359
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             230297 non-null  object
 1   rideable_type       230297 non-null  object
 2   start_station_name  230297 non-null  object
 3   start_station_id    230297 non-null  object
 4   end_station_name    230297 non-null  object
 5   end_station_id      230297 non-null  object
 6   start_lat           230297 non-null  float64
 7   start_lng           230297 non-null  float64
 8   end_lat             230297 non-null  float64
 9   end_lng             230297 non-null  float64
 10  member_casual       230297 non-null  object
 11  start_date          230297 non-null  object
 12  start_time          230297 non-null  datetime64[ns]
 13  end_date            230297 non-null  object
 14  end_time            230297 non-null  datetime64[ns]
 15  duration            230297 non-null  timedelta64[ns]
dtypes: datetime64[ns](2), float64(4), object(9), timedelta64[ns](1)
memory usage: 29.9+ MB

In [128]:
bike_csv["started_at"] = pd.to_datetime(bike_csv["started_at"])
bike_csv["ended_at"] = pd.to_datetime(bike_csv["ended_at"])

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1842236152.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["started_at"] = pd.to_datetime(bike_csv["started_at"])
C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1842236152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["ended_at"] = pd.to_datetime(bike_csv["ended_at"])

In [129]:
bike_csv["start_date"] = bike_csv["started_at"].dt.date
bike_csv["start_time"] = bike_csv["started_at"].dt.time

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1294031612.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["start_date"] = bike_csv["started_at"].dt.date
C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1294031612.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["start_time"] = bike_csv["started_at"].dt.time

In [130]:
bike_csv["end_date"] = bike_csv["ended_at"].dt.date
bike_csv["end_time"] = bike_csv["ended_at"].dt.time

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\2455258601.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["end_date"] = bike_csv["ended_at"].dt.date
C:\Users\karun\AppData\Local\Temp\ipykernel_3228\2455258601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv["end_time"] = bike_csv["ended_at"].dt.time

In [139]:
bike_csv.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time,total_duration
0,AD29C0EB02CCAB09,classic_bike,2024-05-01 16:14:42,2024-05-01 16:25:53,E 6 St & Ave B,5584.04,E 16 St & Irving Pl,5938.11,40.724537,-73.981854,40.735367,-73.987974,member,2024-05-01,1900-01-01 16:14:42,2024-05-01,1900-01-01 16:25:53,11.183333
1,80DD17CA57C45921,electric_bike,2024-05-16 17:57:37,2024-05-16 18:04:30,Scholes St & Manhattan Ave,5108.01,Metropolitan Ave & Bedford Ave,5308.04,40.708651,-73.944878,40.715348,-73.960241,member,2024-05-16,1900-01-01 17:57:37,2024-05-16,1900-01-01 18:04:30,6.883333
2,6EAA75427C2CB2D8,electric_bike,2024-05-23 17:02:35,2024-05-23 17:18:49,Sharon St & Olive St,5323.06,Metropolitan Ave & Bedford Ave,5308.04,40.715340,-73.938393,40.715348,-73.960241,member,2024-05-23,1900-01-01 17:02:35,2024-05-23,1900-01-01 17:18:49,16.233333
3,700278157C0AC354,classic_bike,2024-05-02 06:52:23,2024-05-02 07:01:07,Prospect Park West & 8 St,3722.04,Dean St & Franklin Ave,4107.13,40.665147,-73.976376,40.677592,-73.955637,member,2024-05-02,1900-01-01 06:52:23,2024-05-02,1900-01-01 07:01:07,8.733333
4,00ED91829C30FA66,electric_bike,2024-05-17 20:19:32,2024-05-17 20:33:33,E 2 St & Ave A,5553.10,Metropolitan Ave & Bedford Ave,5308.04,40.723335,-73.986055,40.715348,-73.960241,member,2024-05-17,1900-01-01 20:19:32,2024-05-17,1900-01-01 20:33:33,14.016667

In [108]:
del bike_csv['started_at']
del bike_csv['ended_at']

In [131]:
bike_csv['start_time'] = pd.to_datetime(bike_csv['start_time'], format='%H:%M:%S')

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1135781207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['start_time'] = pd.to_datetime(bike_csv['start_time'], format='%H:%M:%S')

In [132]:
bike_csv['end_time'] = pd.to_datetime(bike_csv['end_time'], format='%H:%M:%S')

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\429088107.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['end_time'] = pd.to_datetime(bike_csv['end_time'], format='%H:%M:%S')

In [133]:
bike_csv['duration']=bike_csv['end_time']-bike_csv['start_time']

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\3122421300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['duration']=bike_csv['end_time']-bike_csv['start_time']

In [64]:
del bike_csv["duration1"]

In [134]:
bike_csv['duration1']=bike_csv['duration'].dt.components.minutes

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\515495748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['duration1']=bike_csv['duration'].dt.components.minutes

In [135]:
bike_csv['duration2']=bike_csv['duration'].dt.components.seconds

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1092742216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['duration2']=bike_csv['duration'].dt.components.seconds

In [136]:
bike_csv['duration2']=bike_csv['duration2']/60

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\1125339702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['duration2']=bike_csv['duration2']/60

In [137]:
bike_csv['total_duration']=bike_csv['duration1']+bike_csv['duration2']

C:\Users\karun\AppData\Local\Temp\ipykernel_3228\4036978477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bike_csv['total_duration']=bike_csv['duration1']+bike_csv['duration2']

In [138]:
del bike_csv['duration']
del bike_csv['duration1']
del bike_csv['duration2']

In [123]:
bike_csv.dropna()

,ride_id,rideable_type,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,start_date,start_time,end_date,end_time,total_duration
0,AD29C0EB02CCAB09,classic_bike,E 6 St & Ave B,5584.04,E 16 St & Irving Pl,5938.11,40.724537,-73.981854,40.735367,-73.987974,member,2024-05-01,1900-01-01 16:14:42,2024-05-01,1900-01-01 16:25:53,11.183333
1,80DD17CA57C45921,electric_bike,Scholes St & Manhattan Ave,5108.01,Metropolitan Ave & Bedford Ave,5308.04,40.708651,-73.944878,40.715348,-73.960241,member,2024-05-16,1900-01-01 17:57:37,2024-05-16,1900-01-01 18:04:30,6.883333
2,6EAA75427C2CB2D8,electric_bike,Sharon St & Olive St,5323.06,Metropolitan Ave & Bedford Ave,5308.04,40.715340,-73.938393,40.715348,-73.960241,member,2024-05-23,1900-01-01 17:02:35,2024-05-23,1900-01-01 17:18:49,16.233333
3,700278157C0AC354,classic_bike,Prospect Park West & 8 St,3722.04,Dean St & Franklin Ave,4107.13,40.665147,-73.976376,40.677592,-73.955637,member,2024-05-02,1900-01-01 06:52:23,2024-05-02,1900-01-01 07:01:07,8.733333
4,00ED91829C30FA66,electric_bike,E 2 St & Ave A,5553.10,Metropolitan Ave & Bedford Ave,5308.04,40.723335,-73.986055,40.715348,-73.960241,member,2024-05-17,1900-01-01 20:19:32,2024-05-17,1900-01-01 20:33:33,14.016667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230355,EA8D2DB4B6B01F2E,classic_bike,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717548,-74.013221,40.760301,-73.998842,member,2024-05-16,1900-01-01 15:03:40,2024-05-16,1900-01-01 15:27:14,23.566667
230356,B4B7E3EC2DDDD247,electric_bike,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717733,-74.013023,40.760301,-73.998842,member,2024-05-14,1900-01-01 14:35:08,2024-05-14,1900-01-01 14:48:28,13.333333
230357,4C646AB4A67E7365,classic_bike,West St & Chambers St,5329.03,11 Ave & W 41 St,6726.01,40.717548,-74.013221,40.760301,-73.998842,member,2024-05-06,1900-01-01 14:11:31,2024-05-06,1900-01-01 14:31:30,19.983333
230358,73EE4AE1389EF161,electric_bike,Bushwick Ave & Powers St,5250.05,Bedford Ave & Nassau Ave,5550.05,40.712562,-73.941067,40.723117,-73.952123,member,2024-05-24,1900-01-01 18:52:49,2024-05-24,1900-01-01 19:01:37,8.800000
230359,38695F4EFCA5BD75,electric_bike,Willoughby Ave & Walworth St,4634.02,Willoughby Ave & Myrtle Ave,4759.02,40.693206,-73.953851,40.697570,-73.930980,member,2024-05-27,1900-01-01 09:43:17,2024-05-27,1900-01-01 09:50:46,7.483333

In [140]:
bike_csv.to_csv("./bike_data.csv")